version: "3.7"

services:
  src:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=src
      - DB_USER=postgres
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_DB=src
  redis:
    image: redis:alpine
  celery:
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - ./src:/src
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - src
  celery-beat:
    build:
      context: .
    command: celery -A core beat -l info
    volumes:
      - ./src:/src
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
volumes:
  pgdata: